//
// This View is inspired by the [Flutter App](https://github.com/fossasia/badgemagic-app) from FOSS ASIA and their Badge Preview
//
import SwiftUI
import Combine

struct LEDPreviewView: View {
    @ObservedObject var message: Message
    @State internal var currentPosition: Double = 0
    @State private var size: CGSize = .zero
    @Environment(\.isEnabled) private var isEnabled
    @Environment(\.colorScheme) var colorScheme

    @State internal var displayBuffer: DisplayBuffer
    
    private let timer = Timer.publish(every: 0.05, on: .main, in: .common).autoconnect()
    
    init(message: Message?) {
        self.message = message ?? Message.placeholder()
        self._displayBuffer = State(initialValue: DisplayBuffer())
    }
    
    // Move computed properties here to make them reactive
    internal var pixels: [[Pixel]] {
        message.getCombinedPixelArrays()
    }
    
    internal var speedMultiplier: Double {
        // This numbers were generated by stopping the time of the actual hardware with a stopwatch
        switch message.speed {
        case .verySlow: return 0.126
        case .slow: return 0.188
        case .relaxed: return 0.257
        case .medium: return 0.329
        case .steady: return 0.466
        case .quick: return 0.797
        case .fast: return 1.125
        case .veryFast: return 2.444
        }
    }
    
    var body: some View {
        TimelineView(.animation) { timeline in
            Canvas { context, size in
                let ledSize = size.width / CGFloat(44)
                let ledSpacing = ledSize / 4
                
                if !isEnabled {
                    context.fill(
                        Path(roundedRect: CGRect(origin: .zero, size: size),
                             cornerRadius: (ledSize / 2) - ledSpacing),
                        with: .color(Color(nsColor: NSColor.separatorColor))
                    )
                    return
                }
                
                // Draw all LEDs in a single pass
                for y in 0..<11 {
                    for x in 0..<44 {
                        let isOn = displayBuffer.get(x, y)
                        let offset = CGSize(
                            width: CGFloat(x) * ledSize + ledSpacing / 2,
                            height: CGFloat(y) * ledSize + ledSpacing / 2
                        )
                        
                        context.translateBy(x: offset.width, y: offset.height)
                        context.fill(
                            Path(ellipseIn: CGRect(origin: .zero, size: CGSize(width: ledSize-2, height: ledSize-2))),
                            with: .color(isOn ? .accentColor : .accentColor.opacity(0.2))
                        )
                        context.translateBy(x: -offset.width, y: -offset.height)
                    }
                }
            }
            .shadow(color: .accentColor.opacity(1), radius: 3)
        }
        .frame(height: 11 * (size.width / 44))
        .getSize($size)
        .onReceive(timer) { _ in
            withAnimation(.linear(duration: 0.05)) {
                updateAnimation()
            }
        }
        // Add onChange modifiers to handle property changes
        .onChange(of: message.pixelGrids) {
            currentPosition = 0  // Reset position when pixels change
        }
        .onChange(of: message.mode) {
            currentPosition = 0  // Reset position when mode changes
        }
    }
    
    private func updateAnimation() {
        // Update position with reactive multiplier
        currentPosition += speedMultiplier
        
        // Clear buffer instead of creating new one
        displayBuffer.clear()
        
        switch message.mode {
        case .left:
            scrollLeft()
        case .right:
            scrollRight()
        case .up:
            scrollUp()
        case .down:
            scrollDown()
        case .fixed:
            displayFixed()
        case .picture:
            displayPicture()
        case .snowflake:
            displaySnowflake()
        case .animation:
            displayAnimation()
        case .laser:
            displayLaser()
        }
        
        // Handle flash effect
        if message.flash && (Int(currentPosition / speedMultiplier) % 20) < 10 {
            displayBuffer.clear()
        }
        
        // Handle marquee effect if needed
        if message.marquee {
            applyMarquee()
        }
    }
}
